require('dotenv').config();
const mongoose = require('mongoose');
const Book = require('../models/Book');
const User = require('../models/User');
const { Cart } = require('../models/CartWishlist');

const books = [
  // ─── FICTION (8 books) ────────────────────────────────────────────────────
  {
    title: 'The Midnight Library',
    author: 'Matt Haig',
    description: 'Between life and death there is a library. When Nora Seed finds herself in the Midnight Library, she has a chance to make things right — to undo every regret and live her best possible life.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780525559474-L.jpg',
    price: 14.99, originalPrice: 18.99,
    genre: ['Fiction', 'Fantasy', 'Contemporary'],
    tags: ['life', 'choices', 'magical realism'],
    publisher: 'Viking', publishedDate: new Date('2020-09-29'),
    pages: 304, format: 'Paperback', stock: 45, featured: true, bestseller: true,
    isbn: '9780525559474',
  },
  {
    title: 'The Seven Husbands of Evelyn Hugo',
    author: 'Taylor Jenkins Reid',
    description: 'Aging Hollywood icon Evelyn Hugo finally decides to tell the truth about her glamorous and scandalous life.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9781501161933-L.jpg',
    price: 13.99, genre: ['Fiction', 'Romance', 'Historical Fiction'],
    tags: ['Hollywood', 'love', 'secrets', 'LGBTQ'],
    publisher: 'Atria Books', publishedDate: new Date('2017-06-13'),
    pages: 400, format: 'Paperback', stock: 55, bestseller: true,
    isbn: '9781501161933',
  },
  {
    title: 'It Ends with Us',
    author: 'Colleen Hoover',
    description: 'A brave and heartbreaking novel that digs into the complexities of love, loss, and what it means to truly begin again.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9781501110368-L.jpg',
    price: 13.99, originalPrice: 17.99,
    genre: ['Fiction', 'Romance', 'Contemporary'],
    tags: ['love', 'heartbreak', 'courage'],
    publisher: 'Atria Books', publishedDate: new Date('2016-08-02'),
    pages: 384, format: 'Paperback', stock: 65, featured: true, bestseller: true,
    isbn: '9781501110368',
  },
  {
    title: 'Verity',
    author: 'Colleen Hoover',
    description: 'Hidden in the pages of an unfinished manuscript, Lowen finds a truth that will change everything.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9781538724736-L.jpg',
    price: 14.99, genre: ['Fiction', 'Thriller', 'Mystery'],
    tags: ['thriller', 'dark', 'suspense'],
    publisher: 'Grand Central Publishing', publishedDate: new Date('2018-12-07'),
    pages: 336, format: 'Paperback', stock: 50, bestseller: true,
    isbn: '9781538724736',
  },
  {
    title: 'The Alchemist',
    author: 'Paulo Coelho',
    description: 'A magical story about Santiago, an Andalusian shepherd boy who journeys to Egypt following a dream of finding treasure.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780062315007-L.jpg',
    price: 11.99, originalPrice: 16.99,
    genre: ['Fiction', 'Classic', 'Adventure'],
    tags: ['destiny', 'journey', 'philosophy'],
    publisher: 'HarperOne', publishedDate: new Date('1988-01-01'),
    pages: 208, format: 'Paperback', stock: 90, bestseller: true, featured: true,
    isbn: '9780062315007',
  },
  {
    title: 'Where the Crawdads Sing',
    author: 'Delia Owens',
    description: 'A novel about a young woman who raised herself in the marshes of the deep South. When a local boy is found dead, she is immediately suspected.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780735224292-L.jpg',
    price: 13.99, originalPrice: 18.00,
    genre: ['Fiction', 'Mystery', 'Historical Fiction'],
    tags: ['nature', 'mystery', 'coming of age'],
    publisher: "G.P. Putnam's Sons", publishedDate: new Date('2018-08-14'),
    pages: 384, format: 'Paperback', stock: 48, bestseller: true,
    isbn: '9780735224292',
  },
  {
    title: 'Tomorrow, and Tomorrow, and Tomorrow',
    author: 'Gabrielle Zevin',
    description: 'Two friends meet as children and go on to create video games together. A story of love, creativity, and the bridges we build and burn.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780593321201-L.jpg',
    price: 15.99, originalPrice: 29.00,
    genre: ['Fiction', 'Contemporary', 'Romance'],
    tags: ['friendship', 'video games', 'creativity'],
    publisher: 'Knopf', publishedDate: new Date('2022-07-05'),
    pages: 416, format: 'Hardcover', stock: 30, newArrival: true, featured: true,
    isbn: '9780593321201',
  },
  {
    title: 'Normal People',
    author: 'Sally Rooney',
    description: 'Connell and Marianne grew up in the same small town. A tender, painful story about two people and the invisible threads that bind them.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780571334650-L.jpg',
    price: 12.99, genre: ['Fiction', 'Romance', 'Contemporary'],
    tags: ['love', 'Ireland', 'relationships'],
    publisher: 'Faber & Faber', publishedDate: new Date('2018-08-30'),
    pages: 288, format: 'Paperback', stock: 38,
    isbn: '9780571334650',
  },

  // ─── FANTASY (8 books) ────────────────────────────────────────────────────
  {
    title: 'The Name of the Wind',
    author: 'Patrick Rothfuss',
    description: 'The tale of Kvothe — from his childhood in a troupe of traveling players to his daringly brazen bid to enter a legendary school of magic.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780756404079-L.jpg',
    price: 12.99, genre: ['Fantasy', 'Adventure', 'Epic Fantasy'],
    tags: ['magic', 'adventure', 'coming of age'],
    publisher: 'DAW Books', publishedDate: new Date('2007-03-27'),
    pages: 662, format: 'Paperback', stock: 30, bestseller: true,
    isbn: '9780756404079',
  },
  {
    title: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    description: 'Bilbo Baggins, a comfortable hobbit, is swept into an epic quest by the wizard Gandalf and a company of dwarves to reclaim a treasure guarded by a dragon.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780547928227-L.jpg',
    price: 10.99, genre: ['Fantasy', 'Classic', 'Adventure'],
    tags: ['dragons', 'adventure', 'classic', 'middle earth'],
    publisher: 'Houghton Mifflin', publishedDate: new Date('1937-09-21'),
    pages: 310, format: 'Paperback', stock: 80, bestseller: true,
    isbn: '9780547928227',
  },
  {
    title: 'A Court of Thorns and Roses',
    author: 'Sarah J. Maas',
    description: 'When a young huntress kills a wolf in the woods, a terrifying creature arrives to demand retribution — dragging her to a magical land of faeries.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9781619634442-L.jpg',
    price: 13.99, originalPrice: 19.99,
    genre: ['Fantasy', 'Romance', 'Adventure'],
    tags: ['faerie', 'romance', 'magic', 'retelling'],
    publisher: 'Bloomsbury', publishedDate: new Date('2015-05-05'),
    pages: 419, format: 'Paperback', stock: 55, bestseller: true, featured: true,
    isbn: '9781619634442',
  },
  {
    title: 'Fourth Wing',
    author: 'Rebecca Yarros',
    description: 'Twenty-year-old Violet enters the most elite and deadly division of a war college — where students ride dragons and magic is wielded as a weapon.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9781649374042-L.jpg',
    price: 17.99, originalPrice: 28.00,
    genre: ['Fantasy', 'Romance', 'Adventure'],
    tags: ['dragons', 'romance', 'war college', 'magic'],
    publisher: 'Entangled: Red Tower Books', publishedDate: new Date('2023-05-02'),
    pages: 512, format: 'Hardcover', stock: 42, bestseller: true, newArrival: true, featured: true,
    isbn: '9781649374042',
  },
  {
    title: 'The Way of Kings',
    author: 'Brandon Sanderson',
    description: 'Roshar is a world of stone and storms. An epic fantasy of war, mystery, and the power of the human spirit across a richly imagined world.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780765326355-L.jpg',
    price: 16.99, originalPrice: 22.00,
    genre: ['Fantasy', 'Epic Fantasy', 'Adventure'],
    tags: ['epic', 'magic system', 'world building'],
    publisher: 'Tor Books', publishedDate: new Date('2010-08-31'),
    pages: 1007, format: 'Paperback', stock: 35, featured: true,
    isbn: '9780765326355',
  },
  {
    title: 'Mistborn: The Final Empire',
    author: 'Brandon Sanderson',
    description: 'For a thousand years the ash fell and no flowers bloomed. For a thousand years the Skaa slaved in misery and lived in fear. A crew of rebels plans the impossible: to overthrow the immortal ruler.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780765311788-L.jpg',
    price: 14.99, originalPrice: 18.99,
    genre: ['Fantasy', 'Epic Fantasy', 'Adventure'],
    tags: ['heist', 'magic', 'rebellion', 'empire'],
    publisher: 'Tor Books', publishedDate: new Date('2006-07-17'),
    pages: 541, format: 'Paperback', stock: 40, bestseller: true,
    isbn: '9780765311788',
  },
  {
    title: 'The Priory of the Orange Tree',
    author: 'Samantha Shannon',
    description: 'A world divided. A queendom without an heir. An ancient enemy awakens. The House of Berethnet has ruled Inys for a thousand years — but fate is turning.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9781635570298-L.jpg',
    price: 16.99, originalPrice: 21.00,
    genre: ['Fantasy', 'Epic Fantasy', 'Romance'],
    tags: ['dragons', 'queendom', 'female protagonist', 'epic'],
    publisher: 'Bloomsbury', publishedDate: new Date('2019-02-26'),
    pages: 848, format: 'Hardcover', stock: 25, newArrival: true,
    isbn: '9781635570298',
  },
  {
    title: 'The Shadow of the Wind',
    author: 'Carlos Ruiz Zafón',
    description: 'In the hidden Cemetery of Forgotten Books in post-war Barcelona, a boy discovers a mysterious novel that will change his life forever.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780143034902-L.jpg',
    price: 13.99, genre: ['Fantasy', 'Mystery', 'Historical Fiction'],
    tags: ['Barcelona', 'books', 'mystery', 'literary'],
    publisher: 'Penguin Books', publishedDate: new Date('2004-01-01'),
    pages: 487, format: 'Paperback', stock: 33, bestseller: true,
    isbn: '9780143034902',
  },

  // ─── SCIENCE FICTION (8 books) ────────────────────────────────────────────
  {
    title: 'Dune',
    author: 'Frank Herbert',
    description: 'Set on the desert planet Arrakis, Dune is the story of Paul Atreides — heir to a noble family tasked with ruling an inhospitable world where the only thing of value is the spice melange.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780441013593-L.jpg',
    price: 11.99, genre: ['Science Fiction', 'Classic', 'Epic Fantasy'],
    tags: ['desert', 'politics', 'religion', 'classic'],
    publisher: 'Ace Books', publishedDate: new Date('1965-08-01'),
    pages: 896, format: 'Paperback', stock: 70, bestseller: true,
    isbn: '9780441013593',
  },
  {
    title: 'Project Hail Mary',
    author: 'Andy Weir',
    description: 'Ryland Grace is the sole survivor on a desperate last-chance mission. If he fails, humanity and the Earth itself will perish.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780593135204-L.jpg',
    price: 17.99, originalPrice: 28.00,
    genre: ['Science Fiction', 'Adventure', 'Thriller'],
    tags: ['space', 'survival', 'science'],
    publisher: 'Ballantine Books', publishedDate: new Date('2021-05-04'),
    pages: 476, format: 'Hardcover', stock: 35, featured: true, newArrival: true,
    isbn: '9780593135204',
  },
  {
    title: 'The Martian',
    author: 'Andy Weir',
    description: 'Astronaut Mark Watney is stranded alone on Mars with no way to contact Earth. He must use his ingenuity to survive on a hostile planet.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780804139021-L.jpg',
    price: 13.99, originalPrice: 16.00,
    genre: ['Science Fiction', 'Adventure', 'Thriller'],
    tags: ['mars', 'survival', 'space', 'humor'],
    publisher: 'Crown Publishers', publishedDate: new Date('2014-02-11'),
    pages: 369, format: 'Paperback', stock: 45, bestseller: true,
    isbn: '9780804139021',
  },
  {
    title: "Ender's Game",
    author: 'Orson Scott Card',
    description: "Andrew 'Ender' Wiggin is humanity's only hope. Recruited to a military school in space, he must prepare for a final, bloody war against a deadly alien race.",
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780812550702-L.jpg',
    price: 12.99, genre: ['Science Fiction', 'Classic', 'Adventure'],
    tags: ['space', 'war', 'strategy', 'youth'],
    publisher: 'Tor Books', publishedDate: new Date('1985-01-15'),
    pages: 352, format: 'Paperback', stock: 40, bestseller: true,
    isbn: '9780812550702',
  },
  {
    title: 'The Three-Body Problem',
    author: 'Liu Cixin',
    description: 'Set against China\'s Cultural Revolution, a secret military project sends signals into space. An alien civilization receives them and begins planning an invasion.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780765382030-L.jpg',
    price: 14.99, originalPrice: 18.99,
    genre: ['Science Fiction', 'Thriller', 'Classic'],
    tags: ['aliens', 'physics', 'China', 'first contact'],
    publisher: 'Tor Books', publishedDate: new Date('2014-11-11'),
    pages: 400, format: 'Paperback', stock: 32, featured: true, newArrival: true,
    isbn: '9780765382030',
  },
  {
    title: 'Fahrenheit 451',
    author: 'Ray Bradbury',
    description: 'In a future America, books are outlawed and firemen burn them. Guy Montag is a fireman who begins to question the society he serves.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9781451673319-L.jpg',
    price: 10.99, originalPrice: 15.99,
    genre: ['Science Fiction', 'Classic', 'Dystopian'],
    tags: ['dystopia', 'books', 'censorship', 'classic'],
    publisher: 'Simon & Schuster', publishedDate: new Date('1953-10-19'),
    pages: 256, format: 'Paperback', stock: 60, bestseller: true,
    isbn: '9781451673319',
  },
  {
    title: 'Neuromancer',
    author: 'William Gibson',
    description: 'The sky above the port was the color of television, tuned to a dead channel. A washed-up hacker is hired for one last job — and the fate of mankind depends on it.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780441569595-L.jpg',
    price: 12.99, genre: ['Science Fiction', 'Classic', 'Thriller'],
    tags: ['cyberpunk', 'hacker', 'AI', 'classic'],
    publisher: 'Ace Books', publishedDate: new Date('1984-07-01'),
    pages: 271, format: 'Paperback', stock: 28,
    isbn: '9780441569595',
  },
  {
    title: 'Klara and the Sun',
    author: 'Kazuo Ishiguro',
    description: 'Klara is an Artificial Friend — observant and curious about the human world. From her place in the store window, she watches the outside world carefully.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780593311295-L.jpg',
    price: 15.99, originalPrice: 28.00,
    genre: ['Science Fiction', 'Fiction', 'Contemporary'],
    tags: ['AI', 'friendship', 'future', 'literary'],
    publisher: 'Knopf', publishedDate: new Date('2021-03-02'),
    pages: 320, format: 'Hardcover', stock: 22, newArrival: true,
    isbn: '9780593311295',
  },

  // ─── SELF-HELP (8 books) ──────────────────────────────────────────────────
  {
    title: 'Atomic Habits',
    author: 'James Clear',
    description: 'A proven framework for improving every day. Practical strategies for forming good habits, breaking bad ones, and mastering tiny behaviors that lead to remarkable results.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780735211292-L.jpg',
    price: 16.99, originalPrice: 27.00,
    genre: ['Self-Help', 'Business', 'Psychology'],
    tags: ['habits', 'productivity', 'self-improvement'],
    publisher: 'Avery', publishedDate: new Date('2018-10-16'),
    pages: 320, format: 'Hardcover', stock: 60, featured: true, bestseller: true,
    isbn: '9780735211292',
  },
  {
    title: 'Think Again',
    author: 'Adam Grant',
    description: 'The ability to rethink and unlearn matters more than what you already know. Adam Grant shows us how to embrace the joy of being wrong.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9781984878106-L.jpg',
    price: 15.99, originalPrice: 28.00,
    genre: ['Self-Help', 'Psychology', 'Business'],
    tags: ['thinking', 'psychology', 'mindset'],
    publisher: 'Viking', publishedDate: new Date('2021-02-02'),
    pages: 307, format: 'Hardcover', stock: 25, newArrival: true,
    isbn: '9781984878106',
  },
  {
    title: 'The Power of Now',
    author: 'Eckhart Tolle',
    description: 'A guide to spiritual enlightenment. True happiness lives in the present moment — not in the past or future.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9781577314806-L.jpg',
    price: 13.99, originalPrice: 17.00,
    genre: ['Self-Help', 'Spirituality', 'Psychology'],
    tags: ['mindfulness', 'spirituality', 'presence'],
    publisher: 'New World Library', publishedDate: new Date('1999-09-01'),
    pages: 229, format: 'Paperback', stock: 50, bestseller: true,
    isbn: '9781577314806',
  },
  {
    title: "Can't Hurt Me",
    author: 'David Goggins',
    description: 'Through self-discipline, mental toughness, and hard work, Goggins transformed himself from a depressed overweight young man into a US Armed Forces icon.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9781544512280-L.jpg',
    price: 16.99, originalPrice: 25.00,
    genre: ['Self-Help', 'Biography', 'Memoir'],
    tags: ['motivation', 'discipline', 'military', 'mindset'],
    publisher: 'Lioncrest Publishing', publishedDate: new Date('2018-12-04'),
    pages: 364, format: 'Hardcover', stock: 38, bestseller: true, featured: true,
    isbn: '9781544512280',
  },
  {
    title: '12 Rules for Life',
    author: 'Jordan B. Peterson',
    description: 'Renowned psychologist Jordan Peterson combines hard-won truths of ancient tradition with the latest insights of neuroscience to offer a path through life\'s chaos.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780345816023-L.jpg',
    price: 15.99, originalPrice: 25.99,
    genre: ['Self-Help', 'Psychology', 'Philosophy'],
    tags: ['rules', 'life', 'psychology', 'philosophy'],
    publisher: 'Random House Canada', publishedDate: new Date('2018-01-23'),
    pages: 448, format: 'Hardcover', stock: 42, bestseller: true,
    isbn: '9780345816023',
  },
  {
    title: 'The 4-Hour Workweek',
    author: 'Timothy Ferriss',
    description: 'Forget the old concept of retirement and the deferred-life plan — there is no need to wait. Whether your dream is escaping the rat race or just living more and working less, this is your blueprint.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780307465351-L.jpg',
    price: 14.99, originalPrice: 19.99,
    genre: ['Self-Help', 'Business', 'Productivity'],
    tags: ['lifestyle', 'productivity', 'freedom', 'entrepreneurship'],
    publisher: 'Crown Publishers', publishedDate: new Date('2007-04-24'),
    pages: 396, format: 'Paperback', stock: 35, bestseller: true,
    isbn: '9780307465351',
  },
  {
    title: 'Ikigai: The Japanese Secret to a Long and Happy Life',
    author: 'Héctor García',
    description: 'The people of Japan believe that everyone has an ikigai — a reason to jump out of bed each morning. This book will help you find yours.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780143130727-L.jpg',
    price: 12.99, originalPrice: 15.99,
    genre: ['Self-Help', 'Philosophy', 'Spirituality'],
    tags: ['japan', 'purpose', 'happiness', 'longevity'],
    publisher: 'Penguin Life', publishedDate: new Date('2017-08-29'),
    pages: 208, format: 'Hardcover', stock: 48, bestseller: true, newArrival: false,
    isbn: '9780143130727',
  },
  {
    title: 'The Subtle Art of Not Giving a F*ck',
    author: 'Mark Manson',
    description: 'A counterintuitive approach to living a good life. Mark Manson argues that improving our lives hinges on embracing what is negative in them.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780062457714-L.jpg',
    price: 13.99, originalPrice: 24.99,
    genre: ['Self-Help', 'Psychology', 'Philosophy'],
    tags: ['mindset', 'values', 'counterintuitive', 'humor'],
    publisher: 'HarperOne', publishedDate: new Date('2016-09-13'),
    pages: 224, format: 'Hardcover', stock: 55, bestseller: true, featured: true,
    isbn: '9780062457714',
  },

  // ─── NON-FICTION (8 books) ────────────────────────────────────────────────
  {
    title: 'Sapiens: A Brief History of Humankind',
    author: 'Yuval Noah Harari',
    description: 'A groundbreaking narrative of humanity\'s creation and evolution — exploring how biology and history have defined us.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780062316097-L.jpg',
    price: 15.99, originalPrice: 19.99,
    genre: ['Non-Fiction', 'History', 'Science'],
    tags: ['history', 'humanity', 'evolution'],
    publisher: 'Harper Perennial', publishedDate: new Date('2015-02-10'),
    pages: 464, format: 'Paperback', stock: 50, featured: true,
    isbn: '9780062316097',
  },
  {
    title: 'The Psychology of Money',
    author: 'Morgan Housel',
    description: 'Timeless lessons on wealth, greed, and happiness. Doing well with money is about how you behave, not what you know.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780857197689-L.jpg',
    price: 14.99, originalPrice: 18.00,
    genre: ['Non-Fiction', 'Business', 'Finance'],
    tags: ['money', 'investing', 'psychology', 'wealth'],
    publisher: 'Harriman House', publishedDate: new Date('2020-09-08'),
    pages: 256, format: 'Hardcover', stock: 40, featured: true, newArrival: true,
    isbn: '9780857197689',
  },
  {
    title: 'Educated',
    author: 'Tara Westover',
    description: 'An unforgettable memoir about a young girl who, kept out of school, leaves her survivalist family and earns a PhD from Cambridge University.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780399590504-L.jpg',
    price: 13.99, originalPrice: 17.00,
    genre: ['Non-Fiction', 'Memoir', 'Biography'],
    tags: ['memoir', 'education', 'family', 'survival'],
    publisher: 'Random House', publishedDate: new Date('2018-02-20'),
    pages: 352, format: 'Paperback', stock: 42, bestseller: true,
    isbn: '9780399590504',
  },
  {
    title: 'Homo Deus: A Brief History of Tomorrow',
    author: 'Yuval Noah Harari',
    description: 'Harari maps out our future. What will happen to democracy when Google and Facebook know our likes and fears better than we know ourselves?',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780062464316-L.jpg',
    price: 15.99, originalPrice: 19.99,
    genre: ['Non-Fiction', 'History', 'Science'],
    tags: ['future', 'AI', 'humanity', 'technology'],
    publisher: 'Harper', publishedDate: new Date('2017-02-21'),
    pages: 464, format: 'Paperback', stock: 35, featured: true,
    isbn: '9780062464316',
  },
  {
    title: 'Outliers: The Story of Success',
    author: 'Malcolm Gladwell',
    description: 'Why do some people succeed far more than others? Gladwell examines the stories of outliers — the best, the brightest, the most famous and successful.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780316017930-L.jpg',
    price: 14.99, originalPrice: 18.99,
    genre: ['Non-Fiction', 'Business', 'Psychology'],
    tags: ['success', 'achievement', 'sociology'],
    publisher: 'Little, Brown and Company', publishedDate: new Date('2008-11-18'),
    pages: 309, format: 'Paperback', stock: 44, bestseller: true,
    isbn: '9780316017930',
  },
  {
    title: 'Born a Crime',
    author: 'Trevor Noah',
    description: 'The compelling, inspiring, and comically sublime story of one man\'s coming-of-age in apartheid South Africa — and a celebration of how laughter can illuminate even the darkest corners.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780399588174-L.jpg',
    price: 14.99, originalPrice: 18.00,
    genre: ['Non-Fiction', 'Memoir', 'Biography'],
    tags: ['South Africa', 'apartheid', 'humor', 'memoir'],
    publisher: 'Spiegel & Grau', publishedDate: new Date('2016-11-15'),
    pages: 304, format: 'Paperback', stock: 38, bestseller: true, newArrival: false,
    isbn: '9780399588174',
  },
  {
    title: 'The Immortal Life of Henrietta Lacks',
    author: 'Rebecca Skloot',
    description: 'Her name was Henrietta Lacks, but scientists know her as HeLa. Her cells were taken without consent in 1951 and became one of the most important tools in medicine.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9781400052189-L.jpg',
    price: 13.99, originalPrice: 16.99,
    genre: ['Non-Fiction', 'Science', 'Biography'],
    tags: ['science', 'ethics', 'medicine', 'race'],
    publisher: 'Broadway Books', publishedDate: new Date('2010-02-02'),
    pages: 381, format: 'Paperback', stock: 26,
    isbn: '9781400052189',
  },
  {
    title: 'Thinking, Fast and Slow',
    author: 'Daniel Kahneman',
    description: 'Nobel Prize winner Kahneman explains the two systems that drive the way we think — System 1 (fast, intuitive) and System 2 (slow, deliberate).',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780374533557-L.jpg',
    price: 15.99, originalPrice: 18.00,
    genre: ['Non-Fiction', 'Psychology', 'Business'],
    tags: ['cognitive bias', 'decision making', 'behavior'],
    publisher: 'Farrar, Straus and Giroux', publishedDate: new Date('2011-10-25'),
    pages: 499, format: 'Paperback', stock: 44, bestseller: true, featured: true,
    isbn: '9780374533557',
  },

  // ─── MYSTERY / THRILLER (8 books) ─────────────────────────────────────────
  {
    title: 'Gone Girl',
    author: 'Gillian Flynn',
    description: "On their fifth wedding anniversary, Nick Dunne's wife Amy disappears. Under media scrutiny, Nick's portrait of a blissful union begins to crumble.",
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780307588364-L.jpg',
    price: 13.99, originalPrice: 16.99,
    genre: ['Mystery', 'Thriller', 'Fiction'],
    tags: ['mystery', 'marriage', 'dark', 'twist'],
    publisher: 'Crown Publishers', publishedDate: new Date('2012-06-05'),
    pages: 422, format: 'Paperback', stock: 48, bestseller: true,
    isbn: '9780307588364',
  },
  {
    title: 'The Girl with the Dragon Tattoo',
    author: 'Stieg Larsson',
    description: "Harriet Vanger disappeared over forty years ago. Her aged uncle continues to seek the truth. A journalist and a hacker team up to investigate.",
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780307949486-L.jpg',
    price: 14.99, originalPrice: 17.99,
    genre: ['Mystery', 'Thriller', 'Fiction'],
    tags: ['Sweden', 'hacker', 'investigation', 'dark'],
    publisher: 'Vintage Crime', publishedDate: new Date('2008-09-16'),
    pages: 672, format: 'Paperback', stock: 36, bestseller: true,
    isbn: '9780307949486',
  },
  {
    title: 'And Then There Were None',
    author: 'Agatha Christie',
    description: 'Ten strangers are lured to an isolated island mansion. One by one, they begin to die according to the lines of a sinister nursery rhyme.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780062073488-L.jpg',
    price: 10.99, originalPrice: 14.99,
    genre: ['Mystery', 'Classic', 'Thriller'],
    tags: ['island', 'murder', 'classic', 'whodunit'],
    publisher: 'HarperCollins', publishedDate: new Date('1939-11-06'),
    pages: 264, format: 'Paperback', stock: 60, bestseller: true,
    isbn: '9780062073488',
  },
  {
    title: 'The Silent Patient',
    author: 'Alex Michaelides',
    description: "Alicia Berenson shoots her husband five times and then never speaks another word. A criminal psychotherapist is determined to uncover her motive.",
    coverImage: 'https://covers.openlibrary.org/b/isbn/9781250301697-L.jpg',
    price: 14.99, originalPrice: 17.99,
    genre: ['Mystery', 'Thriller', 'Fiction'],
    tags: ['psychological', 'silence', 'twist', 'art'],
    publisher: 'Celadon Books', publishedDate: new Date('2019-02-05'),
    pages: 336, format: 'Paperback', stock: 42, bestseller: true,
    isbn: '9781250301697',
  },
  {
    title: 'Big Little Lies',
    author: 'Liane Moriarty',
    description: 'Three women — all mothers — become entangled in a murder mystery that exposes the fractured, frantic love they have for their families.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780425274866-L.jpg',
    price: 13.99, originalPrice: 16.00,
    genre: ['Mystery', 'Fiction', 'Thriller'],
    tags: ['mothers', 'suburban', 'secrets', 'dark humor'],
    publisher: 'Berkley Books', publishedDate: new Date('2014-07-29'),
    pages: 480, format: 'Paperback', stock: 35, bestseller: true,
    isbn: '9780425274866',
  },
  {
    title: 'In the Woods',
    author: 'Tana French',
    description: 'Dublin Murder Squad detective Rob Ryan investigates the murder of a twelve-year-old girl — echoing a childhood incident he cannot remember.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780143113492-L.jpg',
    price: 14.99, genre: ['Mystery', 'Thriller', 'Fiction'],
    tags: ['Dublin', 'detective', 'childhood', 'atmospheric'],
    publisher: 'Penguin Books', publishedDate: new Date('2007-05-17'),
    pages: 429, format: 'Paperback', stock: 28,
    isbn: '9780143113492',
  },
  {
    title: 'The Thursday Murder Club',
    author: 'Richard Osman',
    description: 'Four unlikely friends meet weekly in a retirement village to pore over cold cases. When a local developer is found dead, they find themselves in a real investigation.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9781984880963-L.jpg',
    price: 13.99, originalPrice: 27.00,
    genre: ['Mystery', 'Fiction', 'Thriller'],
    tags: ['cozy mystery', 'retirement', 'humor', 'British'],
    publisher: 'Pamela Dorman Books', publishedDate: new Date('2020-09-03'),
    pages: 382, format: 'Hardcover', stock: 32, newArrival: true,
    isbn: '9781984880963',
  },
  {
    title: 'Rebecca',
    author: 'Daphne du Maurier',
    description: "Last night I dreamt I went to Manderley again. A nameless young woman marries a rich widower and moves to his grand estate — but the shadow of his first wife Rebecca haunts every corner.",
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780380730407-L.jpg',
    price: 11.99, originalPrice: 15.99,
    genre: ['Mystery', 'Classic', 'Romance'],
    tags: ['gothic', 'classic', 'suspense', 'English'],
    publisher: 'Avon Books', publishedDate: new Date('1938-08-11'),
    pages: 449, format: 'Paperback', stock: 40, bestseller: true,
    isbn: '9780380730407',
  },

  // ─── BIOGRAPHY (8 books) ──────────────────────────────────────────────────
  {
    title: 'Becoming',
    author: 'Michelle Obama',
    description: 'Former First Lady Michelle Obama chronicles the experiences that shaped her — from the South Side of Chicago to the White House.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9781524763138-L.jpg',
    price: 16.99, originalPrice: 32.50,
    genre: ['Biography', 'Memoir', 'Non-Fiction'],
    tags: ['obama', 'women', 'politics', 'inspiration'],
    publisher: 'Crown', publishedDate: new Date('2018-11-13'),
    pages: 448, format: 'Hardcover', stock: 55, bestseller: true, featured: true,
    isbn: '9781524763138',
  },
  {
    title: 'Steve Jobs',
    author: 'Walter Isaacson',
    description: 'Based on forty interviews with Jobs over two years, this biography captures the visionary genius behind Apple and Pixar.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9781451648539-L.jpg',
    price: 17.99, originalPrice: 35.00,
    genre: ['Biography', 'Business', 'Non-Fiction'],
    tags: ['apple', 'technology', 'innovation', 'leadership'],
    publisher: 'Simon & Schuster', publishedDate: new Date('2011-10-24'),
    pages: 656, format: 'Hardcover', stock: 30, bestseller: true,
    isbn: '9781451648539',
  },
  {
    title: 'I Am Malala',
    author: 'Malala Yousafzai',
    description: 'The moving memoir of the girl who stood up for education and was shot by the Taliban. Now a global symbol of courage and hope.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780316322409-L.jpg',
    price: 13.99, originalPrice: 18.00,
    genre: ['Biography', 'Memoir', 'Non-Fiction'],
    tags: ['education', 'courage', 'Pakistan', 'girls'],
    publisher: 'Little, Brown and Company', publishedDate: new Date('2013-10-08'),
    pages: 327, format: 'Paperback', stock: 38, bestseller: true,
    isbn: '9780316322409',
  },
  {
    title: 'Long Walk to Freedom',
    author: 'Nelson Mandela',
    description: 'The autobiography of Nelson Mandela — from his rural childhood, through his imprisonment on Robben Island, to his eventual liberation and presidency of South Africa.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780316548182-L.jpg',
    price: 15.99, originalPrice: 20.00,
    genre: ['Biography', 'History', 'Non-Fiction'],
    tags: ['Mandela', 'South Africa', 'freedom', 'apartheid'],
    publisher: 'Back Bay Books', publishedDate: new Date('1994-11-01'),
    pages: 656, format: 'Paperback', stock: 30, bestseller: true,
    isbn: '9780316548182',
  },
  {
    title: 'The Diary of a Young Girl',
    author: 'Anne Frank',
    description: 'The diary of a young Jewish girl who hid with her family in Nazi-occupied Amsterdam during World War II.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780553577129-L.jpg',
    price: 9.99, originalPrice: 12.99,
    genre: ['Biography', 'History', 'Classic'],
    tags: ['WWII', 'Holocaust', 'diary', 'courage'],
    publisher: 'Bantam Books', publishedDate: new Date('1947-06-25'),
    pages: 283, format: 'Paperback', stock: 75, bestseller: true,
    isbn: '9780553577129',
  },
  {
    title: 'Open',
    author: 'Andre Agassi',
    description: 'One of the most fiercely original autobiographies ever written — the story of a celebrated athlete who hated tennis and rediscovered himself through the sport.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780307388407-L.jpg',
    price: 14.99, originalPrice: 28.00,
    genre: ['Biography', 'Memoir', 'Non-Fiction'],
    tags: ['tennis', 'sports', 'identity', 'raw'],
    publisher: 'Vintage Books', publishedDate: new Date('2009-11-09'),
    pages: 386, format: 'Paperback', stock: 22,
    isbn: '9780307388407',
  },
  {
    title: 'Leonardo da Vinci',
    author: 'Walter Isaacson',
    description: 'Based on thousands of pages from his notebooks, Isaacson weaves a narrative that connects da Vinci\'s art to his science and shows how his genius was based on skills we can all develop.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9781501139154-L.jpg',
    price: 17.99, originalPrice: 35.00,
    genre: ['Biography', 'History', 'Non-Fiction'],
    tags: ['art', 'science', 'genius', 'Renaissance'],
    publisher: 'Simon & Schuster', publishedDate: new Date('2017-10-17'),
    pages: 624, format: 'Hardcover', stock: 20, featured: true,
    isbn: '9781501139154',
  },
  {
    title: 'The Story of Art',
    author: 'E.H. Gombrich',
    description: 'One of the most famous and popular books on art ever written — sweeping across the history of art from prehistoric cave paintings to modern works.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780714832470-L.jpg',
    price: 19.99, originalPrice: 39.95,
    genre: ['Biography', 'History', 'Non-Fiction'],
    tags: ['art history', 'classic', 'comprehensive'],
    publisher: 'Phaidon Press', publishedDate: new Date('1950-01-01'),
    pages: 688, format: 'Hardcover', stock: 15,
    isbn: '9780714832470',
  },

  // ─── HISTORY (8 books) ────────────────────────────────────────────────────
  {
    title: 'Guns, Germs, and Steel',
    author: 'Jared Diamond',
    description: 'Why have some civilizations come to dominate others? Diamond examines how geography and environment shaped the modern world.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780393317558-L.jpg',
    price: 15.99, originalPrice: 19.99,
    genre: ['History', 'Non-Fiction', 'Science'],
    tags: ['civilization', 'geography', 'power', 'Pulitzer'],
    publisher: 'W. W. Norton', publishedDate: new Date('1997-03-01'),
    pages: 480, format: 'Paperback', stock: 38, bestseller: true, featured: true,
    isbn: '9780393317558',
  },
  {
    title: 'The Silk Roads',
    author: 'Peter Frankopan',
    description: 'A new history of the world — not from the perspective of the West, but from the ancient trade routes at the heart of Asia that shaped our civilization.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9781101912379-L.jpg',
    price: 16.99, originalPrice: 20.00,
    genre: ['History', 'Non-Fiction', 'Science'],
    tags: ['trade routes', 'Asia', 'global history'],
    publisher: 'Vintage Books', publishedDate: new Date('2015-09-03'),
    pages: 656, format: 'Paperback', stock: 28, featured: true,
    isbn: '9781101912379',
  },
  {
    title: 'SPQR: A History of Ancient Rome',
    author: 'Mary Beard',
    description: 'A bold and original account of Rome by one of the world\'s foremost classicists — from its origins to when it was a superpower of 50 million people.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9781631492228-L.jpg',
    price: 15.99, originalPrice: 18.99,
    genre: ['History', 'Non-Fiction', 'Classic'],
    tags: ['Rome', 'ancient', 'empire', 'politics'],
    publisher: 'Liveright Publishing', publishedDate: new Date('2015-10-20'),
    pages: 606, format: 'Paperback', stock: 22,
    isbn: '9781631492228',
  },
  {
    title: 'The Rise and Fall of the Third Reich',
    author: 'William L. Shirer',
    description: 'The definitive account of Nazi Germany — from Hitler\'s rise to power through the war and the ultimate defeat of the Third Reich.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9781451651683-L.jpg',
    price: 19.99, originalPrice: 25.99,
    genre: ['History', 'Non-Fiction', 'Classic'],
    tags: ['WWII', 'Nazi Germany', 'Hitler', 'definitive'],
    publisher: 'Simon & Schuster', publishedDate: new Date('1960-10-01'),
    pages: 1280, format: 'Paperback', stock: 18, bestseller: true,
    isbn: '9781451651683',
  },
  {
    title: 'A People\'s History of the United States',
    author: 'Howard Zinn',
    description: 'A chronicle of American history from the point of view of — and in the words of — America\'s women, factory workers, African Americans, Native Americans, and working people.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780060838652-L.jpg',
    price: 16.99, originalPrice: 21.99,
    genre: ['History', 'Non-Fiction', 'Classic'],
    tags: ['America', 'people', 'activism', 'social justice'],
    publisher: 'Harper Perennial', publishedDate: new Date('1980-01-01'),
    pages: 784, format: 'Paperback', stock: 25, bestseller: true,
    isbn: '9780060838652',
  },
  {
    title: 'Genghis Khan and the Making of the Modern World',
    author: 'Jack Weatherford',
    description: 'The startling true history of how one extraordinary man from nomadic obscurity created an empire that stretched from the Pacific Ocean to the Danube River.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780609809648-L.jpg',
    price: 14.99, originalPrice: 17.00,
    genre: ['History', 'Biography', 'Non-Fiction'],
    tags: ['Mongol', 'empire', 'conqueror', 'Asia'],
    publisher: 'Broadway Books', publishedDate: new Date('2004-03-23'),
    pages: 320, format: 'Paperback', stock: 20,
    isbn: '9780609809648',
  },
  {
    title: 'The Warmth of Other Suns',
    author: 'Isabel Wilkerson',
    description: 'The epic story of America\'s Great Migration, in which six million Black Americans fled the South for Northern and Western cities between 1915 and 1970.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780679763888-L.jpg',
    price: 16.99, originalPrice: 20.00,
    genre: ['History', 'Non-Fiction', 'Biography'],
    tags: ['migration', 'America', 'race', 'social history'],
    publisher: 'Vintage Books', publishedDate: new Date('2010-09-07'),
    pages: 622, format: 'Paperback', stock: 18, newArrival: false,
    isbn: '9780679763888',
  },
  {
    title: '1776',
    author: 'David McCullough',
    description: 'The stirring story of the year that gave birth to the United States — told through the eyes of George Washington and the Continental Army.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780743226721-L.jpg',
    price: 14.99, originalPrice: 18.00,
    genre: ['History', 'Biography', 'Non-Fiction'],
    tags: ['America', 'revolution', 'Washington', 'independence'],
    publisher: 'Simon & Schuster', publishedDate: new Date('2005-05-24'),
    pages: 386, format: 'Paperback', stock: 24, bestseller: true,
    isbn: '9780743226721',
  },

  // ─── PSYCHOLOGY (8 books) ─────────────────────────────────────────────────
  {
    title: "Man's Search for Meaning",
    author: 'Viktor E. Frankl',
    description: "A Holocaust survivor's account of life in Nazi death camps, and his psychotherapeutic method of finding meaning in all forms of existence.",
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780807014271-L.jpg',
    price: 11.99, originalPrice: 15.00,
    genre: ['Psychology', 'Biography', 'Classic'],
    tags: ['meaning', 'Holocaust', 'survival', 'philosophy'],
    publisher: 'Beacon Press', publishedDate: new Date('1959-01-01'),
    pages: 200, format: 'Paperback', stock: 65, bestseller: true,
    isbn: '9780807014271',
  },
  {
    title: 'The Body Keeps the Score',
    author: 'Bessel van der Kolk',
    description: 'A pioneering researcher transforms our understanding of how trauma affects body, brain, and mind — and how we can begin to heal.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780143127741-L.jpg',
    price: 16.99, originalPrice: 20.00,
    genre: ['Psychology', 'Self-Help', 'Non-Fiction'],
    tags: ['trauma', 'healing', 'neuroscience', 'therapy'],
    publisher: 'Penguin Books', publishedDate: new Date('2014-09-25'),
    pages: 464, format: 'Paperback', stock: 33, newArrival: true, featured: true,
    isbn: '9780143127741',
  },
  {
    title: 'Attached',
    author: 'Amir Levine',
    description: 'Over 60% of adults have an insecure attachment style. This book reveals how our attachment style affects all aspects of our lives — especially our relationships.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9781585429134-L.jpg',
    price: 14.99, originalPrice: 17.99,
    genre: ['Psychology', 'Self-Help', 'Non-Fiction'],
    tags: ['attachment', 'relationships', 'love', 'neuroscience'],
    publisher: 'TarcherPerigee', publishedDate: new Date('2010-12-30'),
    pages: 304, format: 'Paperback', stock: 40, bestseller: true, newArrival: true,
    isbn: '9781585429134',
  },
  {
    title: 'Flow: The Psychology of Optimal Experience',
    author: 'Mihaly Csikszentmihalyi',
    description: 'Named one of the 100 best and most influential books ever published by the Literary Review of Canada. A landmark work by the world\'s leading researcher on positive psychology.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780061339202-L.jpg',
    price: 14.99, originalPrice: 17.99,
    genre: ['Psychology', 'Self-Help', 'Non-Fiction'],
    tags: ['flow', 'happiness', 'optimal experience', 'focus'],
    publisher: 'HarperPerennial', publishedDate: new Date('1990-08-30'),
    pages: 336, format: 'Paperback', stock: 28, bestseller: true,
    isbn: '9780061339202',
  },
  {
    title: 'The Gifts of Imperfection',
    author: 'Brené Brown',
    description: 'Brené Brown encourages us to embrace who we are and to let go of what we think we should be — to cultivate courage, compassion, and connection.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9781592858491-L.jpg',
    price: 13.99, originalPrice: 16.00,
    genre: ['Psychology', 'Self-Help', 'Non-Fiction'],
    tags: ['vulnerability', 'shame', 'courage', 'wholehearted'],
    publisher: 'Hazelden Publishing', publishedDate: new Date('2010-08-27'),
    pages: 160, format: 'Paperback', stock: 35, bestseller: true,
    isbn: '9781592858491',
  },
  {
    title: 'Influence: The Psychology of Persuasion',
    author: 'Robert B. Cialdini',
    description: 'The foundational and essential book on influence and persuasion — explaining the psychology behind why people say yes and how to apply these principles ethically.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780061241895-L.jpg',
    price: 15.99, originalPrice: 19.99,
    genre: ['Psychology', 'Business', 'Self-Help'],
    tags: ['persuasion', 'influence', 'marketing', 'behavior'],
    publisher: 'HarperBusiness', publishedDate: new Date('1984-01-01'),
    pages: 336, format: 'Paperback', stock: 44, bestseller: true, featured: true,
    isbn: '9780061241895',
  },
  {
    title: 'Why We Sleep',
    author: 'Matthew Walker',
    description: 'The first sleep book by a leading scientific expert — explaining how sleep can make us cleverer, more attractive, slimmer, happier, healthier, and ward off cancer.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9781501144325-L.jpg',
    price: 15.99, originalPrice: 28.00,
    genre: ['Psychology', 'Science', 'Self-Help'],
    tags: ['sleep', 'health', 'neuroscience', 'wellness'],
    publisher: 'Scribner', publishedDate: new Date('2017-10-03'),
    pages: 368, format: 'Hardcover', stock: 38, bestseller: true, newArrival: false,
    isbn: '9781501144325',
  },
  {
    title: 'Daring Greatly',
    author: 'Brené Brown',
    description: 'Based on twelve years of research, Brené Brown dispels the cultural myth that vulnerability is a weakness. Vulnerability is actually our most accurate measure of courage.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9781592407330-L.jpg',
    price: 14.99, originalPrice: 27.00,
    genre: ['Psychology', 'Self-Help', 'Non-Fiction'],
    tags: ['vulnerability', 'courage', 'connection', 'shame'],
    publisher: 'Gotham Books', publishedDate: new Date('2012-09-11'),
    pages: 320, format: 'Hardcover', stock: 30,
    isbn: '9781592407330',
  },

  // ─── BUSINESS (8 books) ───────────────────────────────────────────────────
  {
    title: 'Zero to One',
    author: 'Peter Thiel',
    description: 'Every moment in business happens only once. The next Bill Gates will not build an operating system — if you are copying others, you aren\'t learning from them.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780804139021-L.jpg',
    price: 15.99, originalPrice: 27.00,
    genre: ['Business', 'Non-Fiction', 'Self-Help'],
    tags: ['startup', 'innovation', 'entrepreneurship', 'tech'],
    publisher: 'Crown Business', publishedDate: new Date('2014-09-16'),
    pages: 224, format: 'Hardcover', stock: 38, bestseller: true,
    isbn: '9780804139026',
  },
  {
    title: 'Rich Dad Poor Dad',
    author: 'Robert T. Kiyosaki',
    description: "Kiyosaki shares the story of his two dads and the ways in which both men shaped his thoughts about money, investing, and financial independence.",
    coverImage: 'https://covers.openlibrary.org/b/isbn/9781612680194-L.jpg',
    price: 12.99, originalPrice: 17.99,
    genre: ['Business', 'Finance', 'Self-Help'],
    tags: ['money', 'investing', 'financial freedom', 'wealth'],
    publisher: 'Plata Publishing', publishedDate: new Date('1997-04-01'),
    pages: 336, format: 'Paperback', stock: 70, bestseller: true, featured: true,
    isbn: '9781612680194',
  },
  {
    title: 'Good to Great',
    author: 'Jim Collins',
    description: 'Can a good company become a great company and if so, how? Collins and his team studied companies that made the leap from good to great.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780066620992-L.jpg',
    price: 16.99, originalPrice: 29.99,
    genre: ['Business', 'Non-Fiction', 'Self-Help'],
    tags: ['leadership', 'management', 'company', 'strategy'],
    publisher: 'HarperBusiness', publishedDate: new Date('2001-10-16'),
    pages: 320, format: 'Hardcover', stock: 28, bestseller: true,
    isbn: '9780066620992',
  },
  {
    title: 'The Lean Startup',
    author: 'Eric Ries',
    description: 'Most startups fail. But many of those failures are preventable. The Lean Startup is a new approach to business being adopted around the world.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780307887894-L.jpg',
    price: 15.99, originalPrice: 26.00,
    genre: ['Business', 'Non-Fiction', 'Self-Help'],
    tags: ['startup', 'lean', 'MVP', 'innovation'],
    publisher: 'Crown Business', publishedDate: new Date('2011-09-13'),
    pages: 336, format: 'Hardcover', stock: 32, bestseller: true, newArrival: false,
    isbn: '9780307887894',
  },
  {
    title: 'Never Split the Difference',
    author: 'Chris Voss',
    description: 'A former international hostage negotiator for the FBI offers a new, field-tested approach to high-stakes negotiations — whether in the boardroom or at home.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780062407801-L.jpg',
    price: 16.99, originalPrice: 28.99,
    genre: ['Business', 'Psychology', 'Self-Help'],
    tags: ['negotiation', 'FBI', 'communication', 'strategy'],
    publisher: 'Harper Business', publishedDate: new Date('2016-05-17'),
    pages: 288, format: 'Hardcover', stock: 36, bestseller: true, featured: true,
    isbn: '9780062407801',
  },
  {
    title: 'The Hard Thing About Hard Things',
    author: 'Ben Horowitz',
    description: 'Ben Horowitz offers essential advice on building and running a startup — practical wisdom for managing the toughest problems business school doesn\'t cover.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780062273208-L.jpg',
    price: 15.99, originalPrice: 27.99,
    genre: ['Business', 'Non-Fiction', 'Self-Help'],
    tags: ['startup', 'CEO', 'management', 'silicon valley'],
    publisher: 'HarperBusiness', publishedDate: new Date('2014-03-04'),
    pages: 304, format: 'Hardcover', stock: 24,
    isbn: '9780062273208',
  },
  {
    title: 'Shoe Dog',
    author: 'Phil Knight',
    description: 'The memoir by the founder of Nike — a candid and riveting account of how he and his ragtag group of friends and competitors built the most iconic sports brand in the world.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9781501135910-L.jpg',
    price: 15.99, originalPrice: 29.99,
    genre: ['Business', 'Biography', 'Memoir'],
    tags: ['Nike', 'entrepreneurship', 'sports', 'perseverance'],
    publisher: 'Scribner', publishedDate: new Date('2016-04-26'),
    pages: 400, format: 'Hardcover', stock: 30, bestseller: true, newArrival: false,
    isbn: '9781501135910',
  },
  {
    title: 'Principles: Life and Work',
    author: 'Ray Dalio',
    description: 'Ray Dalio, founder of Bridgewater Associates, shares the unconventional principles that helped him create exceptional results in both life and business.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9781501124020-L.jpg',
    price: 19.99, originalPrice: 30.00,
    genre: ['Business', 'Non-Fiction', 'Self-Help'],
    tags: ['principles', 'Bridgewater', 'decision making', 'success'],
    publisher: 'Simon & Schuster', publishedDate: new Date('2017-09-19'),
    pages: 592, format: 'Hardcover', stock: 22, featured: true,
    isbn: '9781501124020',
  },
];

const seedDB = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('✅ Connected to MongoDB');

    await Book.deleteMany({});
    await User.deleteMany({});
    await Cart.deleteMany({});
    console.log('🗑️  Cleared existing data');

    await Book.insertMany(books);
    console.log(`📚 Seeded ${books.length} books`);

    const admin = await User.create({
      name: 'BookHaven Admin',
      email: 'admin@bookhaven.com',
      password: 'Admin@123456',
      role: 'admin',
    });
    await Cart.create({ user: admin._id, items: [] });
    console.log('👤 Admin user created: admin@bookhaven.com / Admin@123456');

    const demo = await User.create({
      name: 'Demo User',
      email: 'demo@bookhaven.com',
      password: 'Demo@123456',
      role: 'user',
    });
    await Cart.create({ user: demo._id, items: [] });
    console.log('👤 Demo user created: demo@bookhaven.com / Demo@123456');

    console.log('\n🌱 Seed complete!');
    process.exit(0);
  } catch (err) {
    console.error('❌ Seed failed:', err);
    process.exit(1);
  }
};

seedDB();